// @ts-nocheck
import { useMemo, useState } from 'react';
import { Activity, ArrowUpRight, Check, ChevronRight, CircleDot, FileCode2, GitBranch, Gauge, LockKeyhole, Play, RotateCcw, Sparkles, Terminal, TriangleAlert, X } from 'lucide-react';
import type { Candidate, Run } from './domain';
import { analyzeFixture, applyCandidates } from './analyzer';
import { runTrueForgeOrchestrator } from './trueforge';
const stages=['Analyze','Opportunities','Optimize','Results'];
const initialEvents=[{id:'e1',label:'Repository Mapper',status:'queued' as const,detail:'Waiting for analysis'},{id:'e2',label:'AI Usage Auditor',status:'queued' as const,detail:'Waiting for analysis'},{id:'e3',label:'Cost Optimization Analyst',status:'queued' as const,detail:'Waiting for analysis'},{id:'e4',label:'Deterministic Replacement Analyst',status:'queued' as const,detail:'Waiting for analysis'},{id:'e5',label:'Test & Benchmark Agent',status:'queued' as const,detail:'Runs after a patch'},{id:'e6',label:'Reviewer Agent',status:'queued' as const,detail:'Checks behavior and risk'}];
export default function App(){
 const[url,setUrl]=useState('fixture://inefficient-ai-app');const[run,setRun]=useState<Run|null>(null);const[stage,setStage]=useState(0);const[filter,setFilter]=useState('All');
 const data=useMemo(()=>run?.candidates.filter(c=>filter==='All'||(filter==='Remove AI'?c.removesAi:c.category===filter||c.confidence===filter)),[run,filter]);
 function analyze(){const result=analyzeFixture();setRun({id:crypto.randomUUID(),repositoryUrl:url,status:'analyzing',createdAt:new Date().toISOString(),...result,events:initialEvents});setStage(0);setTimeout(()=>setRun(c=>c?{...c,status:'ready',events:c.events.map((e,i)=>({...e,status:i<4?'complete':'queued',detail:i<4?'Evidence recorded':e.detail}))}:c),650);}
 async function optimize(){if(!run)return;setStage(2);setRun({...run,status:'optimizing',events:run.events.map(e=>e.label==='Test & Benchmark Agent'?{...e,status:'active',detail:'Running fixture regression suite'}:e)});await runTrueForgeOrchestrator(run.repositoryUrl,()=>undefined);setTimeout(()=>setRun(c=>c?{...c,status:'complete',after:applyCandidates(c.before,c.candidates),events:c.events.map(e=>({...e,status:'complete',detail:e.label==='Reviewer Agent'?'2 accepted · 1 held for review':'Complete'}))}:c),900);}
 function setAccepted(id:string,accepted:boolean){setRun(c=>c?{...c,candidates:c.candidates.map(x=>x.id===id?{...x,accepted}:x)}:c);}
 const before=run?.before,after=run?.after,reduction=before&&after?Math.round((1-after.cost/before.cost)*100):0;
 return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={16}/></span><span>Forge<span className="muted">Optimizer</span></span></div><div className="eyebrow">CONTROL ROOM</div><nav><button className="nav-active"><Activity size={16}/>Optimization run</button><button><GitBranch size={16}/>Repositories</button><button><Gauge size={16}/>Benchmarks</button></nav><div className="sidebar-bottom"><div className="security"><LockKeyhole size={15}/><span>Sandboxed by default</span><span className="dot"/></div><div className="version">V1 · local mode</div></div></aside><main className="main"><header><div><div className="eyebrow">AI EFFICIENCY WORKBENCH</div><h1>Make every model call earn its place.</h1><p className="lede">Find waste in a repository, patch it in isolation, then prove the savings survived the test suite.</p></div><div className="header-status"><span className="live-dot"/> local runtime <span className="slash">/</span> <span className="muted">TrueForge ready</span></div></header><section className="command-bar"><div className="input-wrap"><GitBranch size={17}/><input aria-label="GitHub repository URL" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/you/your-ai-app"/></div><button className="primary" onClick={analyze}><Play size={15} fill="currentColor"/> Analyze repository <ArrowUpRight size={15}/></button></section><div className="stepper">{stages.map((item,index)=><button key={item} className={index===stage?'step active':index<stage?'step done':'step'} onClick={()=>run&&setStage(index)}><span>{index<stage?<Check size={13}/>:`0${index+1}`}</span>{item}</button>)}</div>{!run?<EmptyState onAnalyze={analyze}/>:<><section className="run-strip"><div className="run-title"><span className="pulse"/><div><span className="eyebrow">CURRENT RUN</span><strong>{run.repositoryUrl}</strong></div></div><div className="run-meta"><span>{run.status}</span><span>#{run.id.slice(0,8)}</span><button onClick={()=>setRun(null)} title="Reset run"><RotateCcw size={15}/></button></div></section>{stage===0&&<AnalysisView run={run}/>} {stage===1&&<Opportunities candidates={data??[]} filter={filter} setFilter={setFilter} setAccepted={setAccepted} onOptimize={optimize}/>} {stage===2&&<OptimizationView run={run}/>} {stage===3&&<ResultsView run={run} reduction={reduction}/>}<div className="stage-actions">{stage>0&&<button className="ghost" onClick={()=>setStage(stage-1)}>Back</button>}{stage===0&&run.status==='ready'&&<button className="primary" onClick={()=>setStage(1)}>Review opportunities <ChevronRight size={15}/></button>}{stage===1&&<button className="primary" onClick={optimize}><Play size={15} fill="currentColor"/> Optimize selected</button>}{stage===2&&run.status==='complete'&&<button className="primary" onClick={()=>setStage(3)}>View results <ChevronRight size={15}/></button>}</div></>}</main></div>;
}
function EmptyState({onAnalyze}:{onAnalyze:()=>void}){return <div className="empty"><div className="empty-orbit"><span/><span/><Sparkles size={25}/></div><div className="eyebrow">START WITH A REPOSITORY</div><h2>Turn hidden AI spend into visible engineering work.</h2><p>Try the included fixture to see the full loop: detect → patch → test → benchmark → review.</p><button className="text-button" onClick={onAnalyze}>Run the demo fixture <ArrowUpRight size={15}/></button><div className="empty-note"><Terminal size={14}/> No provider credentials required for static analysis</div></div>}
function AnalysisView({run}:{run:Run}){return <div className="analysis-grid"><div className="panel progress-panel"><div className="panel-head"><div><div className="eyebrow">ORCHESTRATION</div><h2>Agents on the case</h2></div><span className="tiny-badge">{run.events.filter(e=>e.status==='complete').length}/6 complete</span></div><div className="agent-list">{run.events.map(e=><div className="agent" key={e.id}><span className={`agent-icon ${e.status}`}>{e.status==='complete'?<Check size={14}/>:e.status==='active'?<CircleDot size={14}/>:<span/>}</span><div className="agent-copy"><strong>{e.label}</strong><span>{e.detail}</span></div><span className={`status ${e.status}`}>{e.status}</span></div>)}</div><div className="safe-note"><LockKeyhole size={14}/><span>Repository execution is held behind the sandbox boundary.</span></div></div><div className="panel findings-panel"><div className="eyebrow">LIVE SIGNALS</div><div className="signal"><span className="signal-number">{run.usages.length}</span><span>AI call sites mapped</span></div><div className="signal"><span className="signal-number amber">{run.candidates.length}</span><span>optimization candidates</span></div><div className="signal"><span className="signal-number green">{run.candidates.filter(c=>c.confidence==='HIGH').length}</span><span>high-confidence wins</span></div><div className="finding-footer"><FileCode2 size={15}/> TypeScript fixture · 3 files inspected</div></div></div>}
 function Opportunities({candidates,filter,setFilter,setAccepted}:{candidates:Candidate[];filter:string;setFilter:(v:string)=>void;setAccepted:(id:string,a:boolean)=>void}){const filters=['All','HIGH','Remove AI','Context reduction','Cheaper model'];return <div><div className="section-heading"><div><div className="eyebrow">FINDINGS / 05</div><h2>Optimization opportunities</h2><p>Evidence-backed candidates from deterministic source analysis.</p></div><span className="selection">{candidates.filter(c=>c.accepted!==false).length} selected</span></div><div className="filters">{filters.map(x=><button key={x} className={filter===x?'filter active':'filter'} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="candidate-grid">{candidates.map(c=><CandidateCard key={c.id} candidate={c} onToggle={()=>setAccepted(c.id,c.accepted===false)}/>)}</div></div>}
function CandidateCard({candidate:c,onToggle}:{candidate:Candidate;onToggle:()=>void}){return <article className={`candidate ${c.accepted===false?'rejected':''}`}><div className="candidate-top"><span className={`category ${c.category==='Deterministic replacement'?'violet':c.category==='Cheaper model'?'amber-bg':'blue'}`}>{c.category}</span><button className="check-button" onClick={onToggle} title="Toggle candidate">{c.accepted===false?<X size={15}/>:<Check size={15}/>}</button></div><h3>{c.title}</h3><div className="location"><FileCode2 size={13}/>{c.file}<span>:{c.line}</span></div><p>{c.finding}</p><div className="recommendation"><span>RECOMMENDATION</span>{c.recommendation}</div><div className="candidate-foot"><strong>{c.savingsPercent}% <small>potential savings</small></strong><span className={`confidence ${c.confidence.toLowerCase()}`}>{c.confidence}</span><span className="risk">{c.risk} risk</span></div></article>}
function OptimizationView({run}:{run:Run}){return <div className="panel optimization"><div className="panel-head"><div><div className="eyebrow">PATCH PIPELINE</div><h2>Proving the change</h2></div><span className="tiny-badge">{run.status==='complete'?'Run complete':'Working'}</span></div><div className="pipeline">{['Candidate','Patch','Tests','Benchmark','Review'].map((item,i)=><div className={`pipeline-step ${run.status==='complete'||i===0?'complete':'active'}`} key={item}><span>{run.status==='complete'||i===0?<Check size={14}/>:i+1}</span><strong>{item}</strong><small>{run.status==='complete'?(i===4?'2 accepted · 1 held':'passed'):i===0?'selected candidates':'queued'}</small></div>)}</div><div className="diff"><div className="diff-head"><span><FileCode2 size={14}/> src/classifyTicket.ts</span><span>unified diff</span></div><pre><span className="minus">- client.chat.completions.create({`{`} model: 'gpt-4.1' {`}`})</span>{'\n'}<span className="plus">+ return classifyByRules(text);</span></pre></div></div>}
function ResultsView({run,reduction}:{run:Run;reduction:number}){return <div><div className="result-hero"><div><div className="eyebrow">VERIFIED OUTCOME</div><h2>Less AI. Same contract.</h2><p>High-confidence deterministic replacements passed the fixture regression suite.</p></div><div className="result-number">{reduction}%<small>estimated cost reduced</small></div></div><div className="metrics"><Metric label="Before" value={`$${run.before.cost.toFixed(3)}`} sub={`${run.before.calls} calls · ${run.before.tokens.toLocaleString()} tokens`}/><Metric label="After" value={`$${run.after?.cost.toFixed(3)}`} sub={`${run.after?.calls} calls · ${run.after?.tokens.toLocaleString()} tokens`}/><Metric label="Changed files" value="2" sub="patches accepted"/><Metric label="Tests" value="12 / 12" sub="regression suite passed"/></div><div className="result-grid"><div className="panel"><div className="eyebrow">DECISION LOG</div>{run.candidates.map(c=><div className="decision" key={c.id}><span className={c.accepted===false?'decision-icon held':'decision-icon'}>{c.accepted===false?<TriangleAlert size={14}/>:<Check size={14}/>}</span><span>{c.title}</span><strong>{c.accepted===false?'HELD':'ACCEPTED'}</strong></div>)}</div><div className="panel next-panel"><div className="eyebrow">NEXT ACTION</div><h3>Approve the final patch</h3><p>ForgeOptimizer never merges to your default branch automatically. Export the diff for review or create a branch behind an explicit approval.</p><button className="primary"><Check size={15}/> Approve patch</button></div></div></div>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
