import type { AIInvocation, CaptureLevel, SourceLocation } from './domain';
import { estimateInvocationCost, instrumentInvocation } from './v2';

export type ProviderResponse=Record<string,unknown>;
export type ProviderCallInput={provider:string;model?:string;callSite:SourceLocation;captureLevel:CaptureLevel;metadata?:Record<string,unknown>};
function numberAt(value:unknown,...keys:string[]):number|undefined{let current=value;for(const key of keys){if(!current||typeof current!=='object')return undefined;current=(current as Record<string,unknown>)[key];}return typeof current==='number'?current:undefined;}
export function normalizeProviderUsage(provider:string,response:ProviderResponse,requestedModel?:string):Pick<AIInvocation,'model'|'inputTokens'|'outputTokens'|'cost'|'metadata'>{const input=numberAt(response,'usage','prompt_tokens')??numberAt(response,'usage','input_tokens')??numberAt(response,'usage','inputTokens');const output=numberAt(response,'usage','completion_tokens')??numberAt(response,'usage','output_tokens')??numberAt(response,'usage','outputTokens');const finishReason=typeof response.finish_reason==='string'?response.finish_reason:typeof response.stop_reason==='string'?response.stop_reason:undefined;const model=typeof response.model==='string'?response.model:requestedModel;const estimate=estimateInvocationCost({model,inputTokens:input,outputTokens:output});return{model,inputTokens:input,outputTokens:output,cost:Number.isFinite(estimate)?estimate:undefined,metadata:{provider,finishReason,cacheHit:numberAt(response,'usage','cache_read_tokens')!==undefined}};}
export async function instrumentProviderCall<T extends ProviderResponse>(input:ProviderCallInput,operation:()=>Promise<T>):Promise<{value:T;invocation:AIInvocation}>{const result=await instrumentInvocation({provider:input.provider,model:input.model,callSite:input.callSite,captureLevel:input.captureLevel,metadata:{provider:input.provider,model:input.model,...input.metadata}},operation);const usage=normalizeProviderUsage(input.provider,result.value,input.model);return{value:result.value,invocation:{...result.invocation,...usage,metadata:{...result.invocation.metadata,...usage.metadata}}};}
export const instrumentOpenAI=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'OpenAI'},operation);
export const instrumentAnthropic=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'Anthropic'},operation);
export const instrumentGemini=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'Google'},operation);
export const instrumentVercelAI=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'Vercel AI SDK'},operation);
export const instrumentLangChainJS=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'LangChain JS'},operation);
export const instrumentLangChainPython=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'LangChain Python'},operation);
export const instrumentLlamaIndex=(input:Omit<ProviderCallInput,'provider'>,operation:()=>Promise<ProviderResponse>)=>instrumentProviderCall({...input,provider:'LlamaIndex'},operation);
