import type { AgentEvent } from './domain';
import { normalizePatchPayload, type PatchFile } from './patchPayload';

export const trueForgeConfig={url:import.meta.env.VITE_TRUEFORGE_URL??'http://localhost:8790',model:import.meta.env.VITE_TRUEFORGE_MODEL??'openai/gpt-4.1-mini',proxyPath:'/api/trueforge',enabled:import.meta.env.VITE_TRUEFORGE_PROXY_ENABLED==='true'};
type TrueForgeSession={id:string;status?:string};
type TrueForgeTurn={id:string;state?:string};
type TrueForgeEvent={type?:string;id?:string;thread_id?:string;content?:unknown;state?:string;detail?:string;[key:string]:unknown};
export type TrueForgeRunOptions={signal?:AbortSignal;timeoutMs?:number;maxRetries?:number;task?:string};
export type TrueForgeRunResult={mode:'trueforge'|'local-deterministic';sessionId?:string;turnId?:string;finalResult?:unknown;patchFiles?:PatchFile[];fallbackReason?:string;failureReason?:string};

async function trueForgeFetch<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${trueForgeConfig.proxyPath}${path}`,{...init,headers:{'Content-Type':'application/json',...init?.headers}});if(!response.ok)throw new Error(`TrueForge ${response.status}: ${await response.text()}`);return response.json() as Promise<T>;}
function sleep(ms:number,signal?:AbortSignal):Promise<void>{return new Promise((resolve,reject)=>{const timer=setTimeout(resolve,ms);signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(signal.reason??new DOMException('Aborted','AbortError'));},{once:true});});}
async function withRetry<T>(operation:()=>Promise<T>,maxRetries:number,signal?:AbortSignal):Promise<T>{let lastError:unknown;for(let attempt=0;attempt<=maxRetries;attempt++){try{return await operation();}catch(error){lastError=error;if(attempt<maxRetries)await sleep(250*(attempt+1),signal);}}throw lastError instanceof Error?lastError:new Error('TrueForge request failed');}
function mapTrueForgeEvent(event:TrueForgeEvent,onEvent:(event:AgentEvent)=>void){const id=event.thread_id?`tf-thread-${event.thread_id}`:'tf-root';switch(event.type){case'thread.created':onEvent({id,label:event.thread_id&&event.thread_id!=='main'?'TrueForge sub-agent':'Optimization Orchestrator',status:'active',detail:'Sub-agent started'});break;case'thread.done':onEvent({id,label:event.thread_id&&event.thread_id!=='main'?'TrueForge sub-agent':'Optimization Orchestrator',status:'complete',detail:'Sub-agent completed'});break;case'model.message.delta':onEvent({id:'tf-root',label:'Optimization Orchestrator',status:'active',detail:typeof event.content==='string'?event.content.slice(-160):'Model response received'});break;case'action_required':case'tool.approval.required':onEvent({id,label:'TrueForge approval gate',status:'blocked',detail:'TrueForge requested an approval before continuing'});break;case'turn.done':onEvent({id:'tf-root',label:'Optimization Orchestrator',status:'complete',detail:'TrueForge turn completed'});break;case'turn.error':onEvent({id:'tf-root',label:'TrueForge turn',status:'blocked',detail:event.detail??'TrueForge turn failed'});break;}}
function parseEventData(data:string):TrueForgeEvent|undefined{try{const value=JSON.parse(data);return value&&typeof value==='object'?value as TrueForgeEvent:undefined;}catch{return undefined;}}
function extractPatchFiles(value:unknown):PatchFile[]{if(!value||typeof value!=='object')return[];return normalizePatchPayload((value as Record<string,unknown>).files).files;}
async function streamTurn(path:string,init:RequestInit,onEvent:(event:AgentEvent)=>void,signal?:AbortSignal):Promise<{turnId?:string;finalResult?:unknown}>{const response=await fetch(`${trueForgeConfig.proxyPath}${path}`,{...init,signal,headers:{'Content-Type':'application/json',...init.headers}});if(!response.ok)throw new Error(`TrueForge ${response.status}: ${await response.text()}`);if(!response.body){const turn=await response.json() as TrueForgeTurn;return{turnId:turn.id};}const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';let turnId:string|undefined;let finalResult:unknown;while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const records=buffer.split('\n\n');buffer=records.pop()??'';for(const record of records){const data=record.split('\n').filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trim()).join('');if(!data)continue;const event=parseEventData(data);if(!event){onEvent({id:'tf-root',label:'TrueForge stream',status:'blocked',detail:'Ignored malformed TrueForge stream event'});continue;}if(event.type==='turn.created'&&typeof event.id==='string')turnId=event.id;if(event.type==='model.message'&&event.content!==undefined){finalResult=event.content;if(typeof event.content==='string'){try{finalResult=JSON.parse(event.content);}catch{}}}mapTrueForgeEvent(event,onEvent);}}return{turnId,finalResult};}
export async function cancelTrueForgeSession(sessionId:string,signal?:AbortSignal):Promise<void>{await trueForgeFetch(`/sessions/${encodeURIComponent(sessionId)}/cancel`,{method:'POST',signal});}
export async function getTrueForgeCapabilities(){return trueForgeFetch<Record<string,unknown>>('/capabilities');}
export async function runTrueForgeOrchestrator(repositoryUrl:string,onEvent:(event:AgentEvent)=>void,options:TrueForgeRunOptions={}):Promise<TrueForgeRunResult>{if(!trueForgeConfig.enabled)return{mode:'local-deterministic'};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(new Error('TrueForge execution timed out')),options.timeoutMs??120000);const signal=options.signal;const abort=()=>controller.abort(signal?.reason??new DOMException('Aborted','AbortError'));signal?.addEventListener('abort',abort,{once:true});const task=options.task??`Analyze ${repositoryUrl} and return structured optimization evidence.`;onEvent({id:'tf-root',label:'Optimization Orchestrator',status:'active',detail:`Starting TrueForge analysis for ${repositoryUrl}`});const agent={spec:{model:{name:trueForgeConfig.model},instructions:'You are the ForgeOptimizer root orchestrator. Analyze repository evidence, never expose secrets or chain-of-thought, and request approval before external writes.',messages:[{type:'user.message',content:task}],config:{iteration_limit:20,dynamic_sub_agents:{enabled:true},context_management:{compaction:{enabled:true},large_tool_response:{enabled:true}},sandbox:{enabled:true,file_downloads:false}}}};try{const session=await withRetry(()=>trueForgeFetch<TrueForgeSession>('/sessions',{method:'POST',body:JSON.stringify({agent}),signal:controller.signal}),options.maxRetries??2,controller.signal);onEvent({id:'tf-root',label:'Optimization Orchestrator',status:'active',detail:`TrueForge session ${session.id} opened`});const turn=await streamTurn(`/sessions/${encodeURIComponent(session.id)}/turns`,{method:'POST',body:JSON.stringify({input:[{type:'user.message',content:task}],stream:true}),signal:controller.signal},onEvent,controller.signal);return{mode:'trueforge',sessionId:session.id,turnId:turn.turnId,finalResult:turn.finalResult,patchFiles:extractPatchFiles(turn.finalResult)};}catch(error){const reason=error instanceof Error?error.message:'TrueForge request failed';onEvent({id:'tf-root',label:'TrueForge failed',status:'blocked',detail:`${reason}; deterministic fallback active`});return{mode:'local-deterministic',fallbackReason:'trueforge-unavailable',failureReason:reason};}finally{clearTimeout(timeout);signal?.removeEventListener('abort',abort);}}
