import type { AIInvocation, BaselineProfile, Candidate, CaptureLevel, CostProjection, EvaluationCase, EvaluationResult, OptimizationPlan, OptimizationPlanStep, OptimizationPolicy, OptimizationScenario, PullRequestRecord, RunMetrics } from './domain';
import { estimateCost } from './pricing';

export const defaultOptimizationPolicy:OptimizationPolicy={maxBehavioralRisk:'medium',minimumExpectedSavingsPercent:5,allowModelChanges:true,allowPromptChanges:true,allowAiRemoval:true,maxFilesPerPatch:15,requireAllTests:true,requireReviewAgent:true};
export const defaultScenario:OptimizationScenario={id:'scenario-fixture-test',name:'Fixture regression suite',command:'pnpm test',cwd:'.',timeoutMs:120000,expectedExitStatus:0,category:'test',requiredEnv:[]};

const secretPatterns=[/sk-[A-Za-z0-9_-]{12,}/g,/gh[pousr]_[A-Za-z0-9_]{20,}/g,/Bearer\s+[A-Za-z0-9._-]+/gi,/AIza[A-Za-z0-9_-]{20,}/g];
export function redactSecrets(value:string):string{return secretPatterns.reduce((result,pattern)=>result.replace(pattern,'[REDACTED]'),value);}
export function safeMetadata(value:Record<string,unknown>,captureLevel:CaptureLevel):Record<string,unknown>{
 if(captureLevel==='metadata_only')return Object.fromEntries(Object.keys(value).filter(key=>/^(status|finish|usage|provider|model|request|response)/i.test(key)).map(key=>[key,value[key]]));
 if(captureLevel==='full_local_only')return value;
 return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,typeof item==='string'?redactSecrets(item):item]));
}
export function fingerprintRequest(provider:string,model:string|undefined,callSite:string,input:string):string{let hash=2166136261;for(const char of `${provider}:${model??''}:${callSite}:${redactSecrets(input)}`)hash=Math.imul(hash^char.charCodeAt(0),16777619);return `${(hash>>>0).toString(16)}`;}
export function createInvocation(input:Omit<AIInvocation,'id'|'timestamp'>):AIInvocation{return{...input,id:crypto.randomUUID(),timestamp:new Date().toISOString()};}
export async function instrumentInvocation<T>(meta:Omit<AIInvocation,'id'|'timestamp'|'latencyMs'|'error'>,operation:()=>Promise<T>):Promise<{value:T;invocation:AIInvocation}>{const started=performance.now();try{const value=await operation();return{value,invocation:createInvocation({...meta,latencyMs:Math.round(performance.now()-started),error:false})};}catch(error){throw Object.assign(error instanceof Error?error:new Error('Invocation failed'),{invocation:createInvocation({...meta,latencyMs:Math.round(performance.now()-started),error:true})});}}

function jsonEqual(left:unknown,right:unknown):boolean{try{return JSON.stringify(left)===JSON.stringify(right);}catch{return false;}}
export function evaluateCase(test:EvaluationCase,baseline:unknown,candidate:unknown):EvaluationResult{let passed=false;let reason='';switch(test.evaluator){case'exact':case'snapshot':passed=jsonEqual(test.expected,candidate);reason=passed?'Exact output matched':'Output differs from expected';break;case'json':passed=jsonEqual(JSON.parse(String(baseline)),JSON.parse(String(candidate)));reason=passed?'JSON structures matched':'JSON structures differ';break;case'numeric_tolerance':{const expected=Number(test.expected);const actual=Number(candidate);const tolerance=test.tolerance??0;passed=Number.isFinite(actual)&&Math.abs(expected-actual)<=tolerance;reason=`difference ${Math.abs(expected-actual)} ${passed?'within':'exceeds'} tolerance ${tolerance}`;break;}case'regex':passed=new RegExp(String(test.expected)).test(String(candidate));reason=passed?'Regex matched':'Regex did not match';break;case'subset':passed=typeof test.expected==='object'&&test.expected!==null&&typeof candidate==='object'&&candidate!==null&&Object.entries(test.expected as Record<string,unknown>).every(([key,value])=>jsonEqual((candidate as Record<string,unknown>)[key],value));reason=passed?'Expected subset found':'Expected subset missing';break;case'schema':passed=typeof candidate==='object'&&candidate!==null;reason=passed?'Candidate is a structured value':'Candidate is not structured';break;case'http_assertion':passed=Boolean(candidate&&typeof candidate==='object'&&(candidate as {ok?:boolean}).ok);reason=passed?'HTTP assertion passed':'HTTP assertion failed';break;}return{caseId:test.id,baseline,candidate,passed,confidence:test.source==='existing_test'?'HIGH':'MEDIUM',reason};}

export function scoreCandidate(candidate:Candidate,callFrequency=1,testCoverage=1,complexity=1):number{const confidence=candidate.confidence==='HIGH'?1:candidate.confidence==='MEDIUM'?.65:.35;const safety=candidate.risk==='LOW'?1:candidate.risk==='MEDIUM'?.7:.4;return Number(((candidate.savingsPercent/100)*confidence*safety*callFrequency*testCoverage/complexity).toFixed(4));}
export function buildOptimizationPlan(runId:string,candidates:Candidate[],policy:OptimizationPolicy=defaultOptimizationPolicy):OptimizationPlan{const eligible=candidates.filter(candidate=>candidate.savingsPercent>=policy.minimumExpectedSavingsPercent&&(candidate.risk==='LOW'||policy.maxBehavioralRisk!=='low')&&(!candidate.removesAi||policy.allowAiRemoval));const steps:OptimizationPlanStep[]=eligible.map(candidate=>({id:`step-${candidate.id}`,candidateId:candidate.id,title:candidate.title,dependsOn:[],score:scoreCandidate(candidate),status:'queued' as const})).sort((a,b)=>b.score-a.score);const classifier=steps.find(step=>step.candidateId==='c1');const transform=steps.find(step=>step.candidateId==='c2');if(classifier&&transform)transform.dependsOn=[classifier.id];return{id:crypto.randomUUID(),runId,createdAt:new Date().toISOString(),steps,expectedSavingsPercent:eligible.reduce((sum,candidate)=>sum+candidate.savingsPercent/eligible.length,0)||0,risk:eligible.some(candidate=>candidate.risk==='HIGH')?'HIGH':eligible.some(candidate=>candidate.risk==='MEDIUM')?'MEDIUM':'LOW'};}

export function projectSavings(before:RunMetrics,after:RunMetrics,requestsPerDay:number,quality:CostProjection['quality']='ESTIMATED'):CostProjection{const measuredPerRun=Math.max(0,before.cost-after.cost);const dailySavings=measuredPerRun*requestsPerDay;return{measuredPerRun,requestsPerDay,dailySavings,monthlySavings:dailySavings*30,annualSavings:dailySavings*365,quality};}
export function baselineFromRun(runId:string,commitSha:string,scenario:OptimizationScenario,metrics:RunMetrics,invocations:AIInvocation[]=[]):BaselineProfile{return{id:crypto.randomUUID(),runId,commitSha,capturedAt:new Date().toISOString(),scenarioId:scenario.id,invocations,testsPassed:0,testsFailed:0,tokens:metrics.tokens,cost:metrics.cost,latencyMs:metrics.latencyMs,outputs:[],quality:metrics.quality==='INFERRED'?'NOT_VERIFIED':metrics.quality};}
export function formatPullRequestReport(metrics:{before:RunMetrics;after?:RunMetrics},candidates:Candidate[],branch:PullRequestRecord['branch']):string{const after=metrics.after;const savings=after?Math.max(0,(1-after.cost/metrics.before.cost)*100):0;return`# ForgeOptimizer AI Efficiency Report\n\n## Estimated impact\n\n- AI calls: ${metrics.before.calls} → ${after?.calls??'NOT VERIFIED'}\n- Tokens: ${metrics.before.tokens.toLocaleString()} → ${after?.tokens.toLocaleString()??'NOT VERIFIED'}\n- Estimated savings: ${after?`${savings.toFixed(1)}%`:'NOT VERIFIED'}\n\n## Optimizations\n\n${candidates.filter(candidate=>candidate.accepted!==false).map(candidate=>`- ${candidate.title}`).join('\n')||'- None approved'}\n\n## Validation\n\n- Tests and behavioral evaluations must be attached from the exact baseline commit.\n- Base: ${branch.baseBranch} @ ${branch.baseCommitSha}\n- Optimization branch: ${branch.optimizationBranch}\n\nGenerated by ForgeOptimizer.`;}

export function estimateInvocationCost(invocation:Pick<AIInvocation,'model'|'inputTokens'|'outputTokens'>):number{return estimateCost(invocation.model??'unknown',invocation.inputTokens??0,invocation.outputTokens??0).value;}
