import type { AIInvocation, BaselineProfile, Candidate, CaptureLevel, CostProjection, EvaluationCase, EvaluationResult, OptimizationPlan, OptimizationPlanStep, OptimizationPolicy, OptimizationScenario, PullRequestRecord, RunMetrics } from './domain';
import { estimateCost } from './pricing';

export const defaultOptimizationPolicy:OptimizationPolicy={maxBehavioralRisk:'medium',minimumExpectedSavingsPercent:5,allowModelChanges:true,allowPromptChanges:true,allowAiRemoval:true,maxFilesPerPatch:15,requireAllTests:true,requireReviewAgent:true};
export const defaultScenario:OptimizationScenario={id:'scenario-fixture-test',name:'Fixture regression suite',command:'pnpm test',cwd:'.',timeoutMs:120000,expectedExitStatus:0,category:'test',requiredEnv:[]};

const secretPatterns=[/sk-[A-Za-z0-9_-]{12,}/gi,/gh[pousr]_[A-Za-z0-9_]{20,}/gi,/Bearer\s+[A-Za-z0-9._-]+/gi,/AIza[A-Za-z0-9_-]{20,}/gi];
export function redactSecrets(value:string):string{return secretPatterns.reduce((result,pattern)=>result.replace(pattern,'[REDACTED]'),value);}
function sanitize(value:unknown):unknown{if(typeof value==='string')return redactSecrets(value);if(Array.isArray(value))return value.map(sanitize);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,/prompt|content|authorization|token|secret|key/i.test(key)?'[REDACTED]':sanitize(item)]));return value;}
export function safeMetadata(value:Record<string,unknown>,captureLevel:CaptureLevel):Record<string,unknown>{
 if(captureLevel==='full_local_only')return value;
 const sanitized=sanitize(value) as Record<string,unknown>;
 if(captureLevel==='metadata_only')return Object.fromEntries(Object.entries(sanitized).filter(([key])=>/^(status|finish|usage|provider|model|request|response|latency|error|cache)/i.test(key)));
 return sanitized;
}
export function fingerprintRequest(provider:string,model:string|undefined,callSite:string,input:string):string{let hash=2166136261;for(const char of `${provider}:${model??''}:${callSite}:${redactSecrets(input)}`)hash=Math.imul(hash^char.charCodeAt(0),16777619);return `${(hash>>>0).toString(16)}`;}
export function createInvocation(input:Omit<AIInvocation,'id'|'timestamp'>):AIInvocation{return{...input,id:crypto.randomUUID(),timestamp:new Date().toISOString()};}
export async function instrumentInvocation<T>(meta:Omit<AIInvocation,'id'|'timestamp'|'latencyMs'|'error'>,operation:()=>Promise<T>):Promise<{value:T;invocation:AIInvocation}>{const started=performance.now();try{const value=await operation();return{value,invocation:createInvocation({...meta,latencyMs:Math.round(performance.now()-started),error:false})};}catch(error){throw Object.assign(error instanceof Error?error:new Error('Invocation failed'),{invocation:createInvocation({...meta,latencyMs:Math.round(performance.now()-started),error:true})});}}

function jsonEqual(left:unknown,right:unknown):boolean{if(Object.is(left,right))return true;if(Array.isArray(left)&&Array.isArray(right))return left.length===right.length&&left.every((item,index)=>jsonEqual(item,right[index]));if(left&&right&&typeof left==='object'&&typeof right==='object'){const a=left as Record<string,unknown>;const b=right as Record<string,unknown>;const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(key=>key in b&&jsonEqual(a[key],b[key]));}return false;}
function subset(expected:unknown,actual:unknown):boolean{if(expected&&typeof expected==='object'&&actual&&typeof actual==='object'&&!Array.isArray(expected)&&!Array.isArray(actual))return Object.entries(expected as Record<string,unknown>).every(([key,value])=>key in (actual as Record<string,unknown>)&&subset(value,(actual as Record<string,unknown>)[key]));return jsonEqual(expected,actual);}
function schemaMatches(expected:unknown,actual:unknown):boolean{if(expected===null||actual===null||typeof expected!==typeof actual||Array.isArray(expected)!==Array.isArray(actual))return expected===actual;if(Array.isArray(expected))return expected.length===0||((actual as unknown[]).every(item=>schemaMatches(expected[0],item)));if(typeof expected==='object')return Object.entries(expected as Record<string,unknown>).every(([key,value])=>key in (actual as Record<string,unknown>)&&schemaMatches(value,(actual as Record<string,unknown>)[key]));return true;}
function baselineEquivalent(test:EvaluationCase,baseline:unknown,candidate:unknown):boolean{switch(test.evaluator){case'exact':case'snapshot':return jsonEqual(baseline,candidate);case'json':return jsonEqual(typeof baseline==='string'?JSON.parse(baseline):baseline,typeof candidate==='string'?JSON.parse(candidate):candidate);case'numeric_tolerance':return Number.isFinite(Number(baseline))&&Number.isFinite(Number(candidate))&&Math.abs(Number(baseline)-Number(candidate))<=(test.tolerance??0);case'regex':{const pattern=new RegExp(String(test.expected));return pattern.test(String(baseline))&&pattern.test(String(candidate));}case'schema':return schemaMatches(test.expected,baseline)&&schemaMatches(test.expected,candidate);case'subset':case'http_assertion':return subset(test.expected,baseline)&&subset(test.expected,candidate);}}
export function evaluateCase(test:EvaluationCase,baseline:unknown,candidate:unknown):EvaluationResult{let passed=false;let reason='';try{switch(test.evaluator){case'exact':case'snapshot':passed=jsonEqual(test.expected,candidate);reason=passed?'Exact output matched':'Output differs from expected';break;case'json':{const expected=typeof test.expected==='string'?JSON.parse(test.expected):test.expected;const actual=typeof candidate==='string'?JSON.parse(candidate):candidate;passed=jsonEqual(expected,actual);reason=passed?'JSON structures matched':'JSON structures differ';break;}case'numeric_tolerance':{const expected=Number(test.expected);const actual=Number(candidate);const tolerance=test.tolerance??0;passed=Number.isFinite(actual)&&Math.abs(expected-actual)<=tolerance;reason=`difference ${Math.abs(expected-actual)} ${passed?'within':'exceeds'} tolerance ${tolerance}`;break;}case'regex':passed=new RegExp(String(test.expected)).test(String(candidate));reason=passed?'Regex matched':'Regex did not match';break;case'subset':passed=subset(test.expected,candidate);reason=passed?'Expected subset found':'Expected subset missing';break;case'schema':passed=schemaMatches(test.expected,candidate);reason=passed?'Candidate matches expected schema':'Candidate does not match expected schema';break;case'http_assertion':passed=subset(test.expected,candidate);reason=passed?'HTTP assertion passed':'HTTP assertion failed';break;}if(passed&&!baselineEquivalent(test,baseline,candidate)){passed=false;reason='Candidate differs from the exact baseline result';}}catch(error){passed=false;reason=`Evaluator error: ${error instanceof Error?error.message:'invalid test input'}`;}return{caseId:test.id,baseline,candidate,passed,confidence:test.source==='existing_test'?'HIGH':'MEDIUM',reason};}

export function scoreCandidate(candidate:Candidate,callFrequency=1,testCoverage=1,complexity=1):number{const confidence=candidate.confidence==='HIGH'?1:candidate.confidence==='MEDIUM'?.65:.35;const safety=candidate.risk==='LOW'?1:candidate.risk==='MEDIUM'?.7:.4;return Number(((candidate.savingsPercent/100)*confidence*safety*callFrequency*testCoverage/complexity).toFixed(4));}
export function buildOptimizationPlan(runId:string,candidates:Candidate[],policy:OptimizationPolicy=defaultOptimizationPolicy):OptimizationPlan{const allowedRisk=policy.maxBehavioralRisk==='low'?['LOW']:policy.maxBehavioralRisk==='medium'?['LOW','MEDIUM']:['LOW','MEDIUM','HIGH'];const eligible=candidates.filter(candidate=>candidate.savingsPercent>=policy.minimumExpectedSavingsPercent&&allowedRisk.includes(candidate.risk)&&(!candidate.removesAi||policy.allowAiRemoval));const steps:OptimizationPlanStep[]=eligible.map(candidate=>({id:`step-${candidate.id}`,candidateId:candidate.id,title:candidate.title,dependsOn:(candidate.dependsOn??[]).map(id=>`step-${id}`),score:scoreCandidate(candidate),status:'queued' as const})).sort((a,b)=>b.score-a.score);return{id:crypto.randomUUID(),runId,createdAt:new Date().toISOString(),steps,expectedSavingsPercent:eligible.reduce((sum,candidate)=>sum+candidate.savingsPercent/eligible.length,0)||0,risk:eligible.some(candidate=>candidate.risk==='HIGH')?'HIGH':eligible.some(candidate=>candidate.risk==='MEDIUM')?'MEDIUM':'LOW'};}

export function projectSavings(before:RunMetrics,after:RunMetrics,requestsPerDay:number,quality:CostProjection['quality']='ESTIMATED'):CostProjection{const measuredPerRun=Math.max(0,before.cost-after.cost);const dailySavings=measuredPerRun*requestsPerDay;return{measuredPerRun,requestsPerDay,dailySavings,monthlySavings:dailySavings*30,annualSavings:dailySavings*365,quality};}
export function baselineFromRun(runId:string,commitSha:string,scenario:OptimizationScenario,metrics:RunMetrics,invocations:AIInvocation[]=[]):BaselineProfile{return{id:crypto.randomUUID(),runId,commitSha,capturedAt:new Date().toISOString(),scenarioId:scenario.id,invocations,testsPassed:0,testsFailed:0,tokens:metrics.tokens,cost:metrics.cost,latencyMs:metrics.latencyMs,outputs:[],quality:metrics.quality==='INFERRED'?'NOT_VERIFIED':metrics.quality};}
export function formatPullRequestReport(metrics:{before:RunMetrics;after?:RunMetrics},candidates:Candidate[],branch:PullRequestRecord['branch']):string{const after=metrics.after;const savings=after&&metrics.before.cost>0?Math.max(0,(1-after.cost/metrics.before.cost)*100):undefined;return`# ForgeOptimizer AI Efficiency Report\n\n## Estimated impact\n\n- AI calls: ${metrics.before.calls} → ${after?.calls??'NOT VERIFIED'}\n- Tokens: ${metrics.before.tokens.toLocaleString()} → ${after?.tokens.toLocaleString()??'NOT VERIFIED'}\n- Estimated savings: ${savings===undefined?'NOT VERIFIED':`${savings.toFixed(1)}%`}\n\n## Optimizations\n\n${candidates.filter(candidate=>candidate.accepted!==false).map(candidate=>`- ${candidate.title}`).join('\n')||'- None approved'}\n\n## Validation\n\n- Tests and behavioral evaluations must be attached from the exact baseline commit.\n- Base: ${branch.baseBranch} @ ${branch.baseCommitSha}\n- Optimization branch: ${branch.optimizationBranch}\n\nGenerated by ForgeOptimizer.`;}

export function estimateInvocationCost(invocation:Pick<AIInvocation,'model'|'inputTokens'|'outputTokens'>):number{const estimate=estimateCost(invocation.model??'unknown',invocation.inputTokens??0,invocation.outputTokens??0);return estimate.quality==='ESTIMATED'?estimate.value:NaN;}
